# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  displayName: Get version pom.xml
  inputs:
    targetType: 'inline'
    script: |
     [xml]$pomXml = Get-Content .\pom.xml
     # version
     $version=$pomXml.project.version
     $artifactId=$pomXml.project.artifactId
     $appName=$artifactId + "-v"+$version.Split(".")[0]
     Write-Host $version
     Write-Host $artifactId
     Write-Host $appName
     Write-Host "##vso[task.setvariable variable=version]$version"
     Write-Host "##vso[task.setvariable variable=artifactId]$artifactId"
     Write-Host "##vso[task.setvariable variable=appName]$appName"
    workingDirectory: '$(Build.SourcesDirectory)'

# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     publishJUnitResults: false
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.11'
#     mavenVersionOption: 'Default'
#     mavenOptions: '-Xmx3072m'
#     mavenAuthenticateFeed: false
#     effectivePomSkip: false
#     sonarQubeRunAnalysis: false
