apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{appName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{appName}}
  template:
    metadata:
      labels:
        app: {{appName}}
    spec:
      containers:
      - name: {{appName}}
        image: {{repositoryImage}}/{{appName}}:{{version}}
        ports:
        - containerPort: 8081